version: '3'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: z9BIE3A2tNHJJqXY
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  neo4j:
    image: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data

  django:
    build:
      target: dev-envs
      context: ./app/
      dockerfile: Dockerfile
    image: django-barista:latest
    restart: unless-stopped
    volumes:
      # - ./app:/app
      - ./:/workspace
    ports:
      - "8080:8000"
    depends_on:
      - postgres
      - neo4j

volumes:
  neo4j-data:
  postgres-data:
