# Generated by Django 4.2 on 2024-02-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SGBDRProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Prix')),
            ],
            options={
                'verbose_name': 'SGBDR Product',
                'verbose_name_plural': 'SGBDR Products',
            },
        ),
    ]
