# Generated by Django 4.2 on 2024-02-27 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_users', '0002_postgresuser_delete_sgbdruser'),
        ('products', '0002_postgresproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SGBDRProduct',
        ),
    ]
