# Generated by Django 4.2 on 2024-02-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SGBDRUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Name')),
                ('forename', models.CharField(verbose_name='Forename')),
                ('products', models.ManyToManyField(related_name='buyers', to='products.sgbdrproduct', verbose_name='Buyed products')),
                ('users', models.ManyToManyField(related_name='followers', to='social_users.sgbdruser', verbose_name='Followed users')),
            ],
        ),
    ]
