# Generated by Django 4.2 on 2024-02-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_postgresproduct'),
        ('social_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostgresUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(verbose_name='First name')),
                ('last_name', models.CharField(verbose_name='Last name')),
                ('products', models.ManyToManyField(related_name='buyers', to='products.postgresproduct', verbose_name='Buyed products')),
                ('users', models.ManyToManyField(related_name='followers', to='social_users.postgresuser', verbose_name='Followed users')),
            ],
        ),
        migrations.DeleteModel(
            name='SGBDRUser',
        ),
    ]
