# Generated by Django 4.2 on 2024-02-27 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_sgbdrproduct'),
        ('social_users', '0002_postgresuser_delete_sgbdruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgresuser',
            name='products',
        ),
        migrations.AlterField(
            model_name='postgresuser',
            name='users',
            field=models.ManyToManyField(null=True, related_name='followers', to='social_users.postgresuser', verbose_name='Followed users'),
        ),
        migrations.AddField(
            model_name='postgresuser',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyers', to='products.postgresproduct', verbose_name='Buyed products'),
        ),
    ]
