# Generated by Django 4.2 on 2024-02-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_sgbdrproduct'),
        ('social_users', '0003_remove_postgresuser_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgresuser',
            name='products',
        ),
        migrations.AlterField(
            model_name='postgresuser',
            name='users',
            field=models.ManyToManyField(related_name='followers', to='social_users.postgresuser', verbose_name='Followed users'),
        ),
        migrations.AddField(
            model_name='postgresuser',
            name='products',
            field=models.ManyToManyField(related_name='buyers', to='products.postgresproduct', verbose_name='Buyed products'),
        ),
    ]
